### PR TITLE
NANO fix

### PR DESCRIPTION
**Pull request by pokemaster974**
Fix the modification for the NANO/XRB ticker

ONT issue stills here.

### CODE REVIEW

**Comment by ManuCart** [comment]
No need to merge because NANO in Binance is same as Coinmarketcap.
Why this fix?
XRB no use anymore

**Comment by ManuCart** [comment]
For ONT need to be wait from coinmarketcap should be rank <400

**Comment by ManuCart** [comment]
Are you sure your XRB come from Binance?
Because Binance return NANO
For ONT need to wait less than 1 week

**Comment by pokemaster974** [comment]
Yes sure. But maybe it was an issue from my previous script (I've checked it was the same script on your repo but I could made a mistake). The most important is if the current script works for everyone except me, so my pull request is unrelevant. I close it.

**Pull request closed without merging**
